### ISSUE TITLE
app crashing?

### ISSUE THREAD

**Issue by thaynos** [manuGMG/1fichier-dl#29]
im trying to install a game rom but the app keeps crashing
```
C:\Users\GUEST1234\Downloads\1fichier-dl-win32-v0.1.4-cli>C:\Users\GUEST1234\Downloads\1fichier-dl-win32-v0.1.4-cli\1fichier-dl.exe https://1fichier.com/?vegpou6up7lg9fq6jfss&af=3390261
Starting download: https://1fichier.com/?vegpou6up7lg9fq6jfss..
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 531, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 20, in <module>
  File "core\download\cli_download.py", line 30, in download
  File "core\download\helpers.py", line 14, in get_proxy
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[13708] Failed to execute script cli
'af' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by manuGMG** [comment]
Thanks for the logs. Which operating system are you using?

**Comment by thaynos** [comment]
windows

**Comment by manuGMG** [comment]
CLI version was removed from main branch.

Test with new GUI release (v0.1.5) and see if this error persists.

**Comment by manuGMG** [comment]
Closing this issue as this error has already been reported [here](https://github.com/manuGMG/1fichier-dl/issues/8#issuecomment-886264815).
